import type { Metadata, Viewport } from "next";
import Link from "next/link";
import Script from "next/script";
import { Inter, Noto_Serif_SC, JetBrains_Mono } from "next/font/google";
import HistorySidebar from "@/components/HistorySidebar";
import JsonLd from "@/components/JsonLd";
import NetworkBanner from "@/components/NetworkBanner";
import TopNav from "@/components/TopNav";
import OnboardingTour from "@/components/OnboardingTour";
import CommandPaletteProvider from "@/components/CommandPaletteProvider";
import { ThemeProvider } from "@/components/ThemeProvider";
