import { chromium } from 'playwright';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
await page.goto('http://localhost:8765/index.html');
await page.waitForSelector('.ask-searchbox', { timeout: 5000 });
await page.screenshot({ path: 'screenshots/integration-desktop-empty.png', fullPage: false });
await page.locator('#ask-input').focus();
await page.waitForTimeout(300);
await page.screenshot({ path: 'screenshots/integration-desktop-focused.png', fullPage: false });
await page.locator('#ask-input').fill('为什么硅谷银行挤兑后市场反应这么剧烈？');
await page.waitForTimeout(300);
await page.screenshot({ path: 'screenshots/integration-desktop-filled.png', fullPage: false });
const mobileCtx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
const mp = await mobileCtx.newPage();
await mp.goto('http://localhost:8765/index.html');
await mp.waitForSelector('.ask-searchbox', { timeout: 5000 });
await mp.screenshot({ path: 'screenshots/integration-mobile-empty.png', fullPage: false });
await browser.close();
console.log('integration screenshots saved');
