"""Shared valid payloads for deep-report contract tests."""

def report_payload() -> dict:
    return {
        "schema_version": "deep-analysis-report-v2",
        "evidence_level": "candidate",
        "generation_status": "validated",
        "shared_structure": {
            "status": "candidate",
            "name": "延迟反馈候选",
            "formal_expression": "x_{t+1}=f(x_t,u_{t-d})",
            "intuition": "两边都可能出现行动晚于状态变化的现象，值得比较反馈时滞。",
            "observations": [{
                "signal_to_check": "两个描述是否都在响应滞后后出现过冲。",
                "candidate_implication": "若该信号在预注册数据中出现，延迟反馈值得继续比较。",
                "status": "not_checked",
            }],
            "competing_explanations": ["共同趋势也可能造成相似轨迹，而不需要共享机制。"],
            "evidence_gaps": ["目标问题尚无逐时观测数据。"],
            "failure_conditions": ["若去除反馈延迟后过冲不变，应否定该候选。"],
        },
        "your_problem_breakdown": {
            "summary": "目标问题表现为补货决策晚于需求变化，库存随后反向过冲。",
            "key_variables": [{
                "name": "补货延迟", "description": "决策到库存变化的时间差", "role": "parameter",
            }],
            "dynamics": "需求冲击先变化，补货命令随后到达，可能形成反向修正。",
            "why_stuck": "只有汇总数据时，趋势与反馈时滞难以区分。",
            "fingerprint_revision": 2,
            "uncertain_points": ["尚不清楚过冲是否由同一批订单造成。"],
        },
        "target_domain_intro": {
            "domain_name": "供应链",
            "what_record_says": "内部记录描述了延迟反馈下的候选过冲模式。",
            "corresponding_phenomenon": {
                "name": "牛鞭效应记录",
                "plain_description": "订单变化逐层传播时，延迟可能放大上下游波动。",
                "source_ref_ids": ["kb-source"],
            },
            "source_limitations": [
                "仅为内部 KB 候选记录；系统综述、独立复现与专家审查均未记录。"
            ],
            "candidate_methods": [{
                "name": "滞后相关检查",
                "proposal_status": "unverified_proposal",
                "why_considered": "时间顺序是区分反馈时滞与共同趋势的一条候选线索。",
                "source_support": "not_recorded",
                "evidence_required": "需要带时间戳的需求、订单与库存序列。",
            }],
        },
        "structural_mapping": {
            "status": "untested",
            "rationale": "两边都可先按延迟反馈候选建模，但因果方向仍需数据区分。",
            "parameter_map": [{
                "source_concept": "传播延迟",
                "source_explanation": "上游变化到下游响应的时间差",
                "target_concept": "补货延迟",
                "target_explanation": "需求变化到补货入库的时间差",
                "support_status": "hypothesis",
                "mapping_hypothesis": "两个时间差可能承担相近的反馈位置。",
                "evidence_for": [],
                "evidence_against": ["当前没有统一采样频率。"],
                "observable_test": "比较不同滞后下的预测误差。",
                "failure_signal": "零滞后模型持续优于延迟模型时停止该映射。",
            }],
            "competing_explanations": ["季节性需求可在没有反馈放大的情况下制造过冲。"],
        },
        "borrowable_insights": [{
            "tool": "滞后模型候选",
            "proposal_status": "unverified_proposal",
            "why_considered": "响应晚于输入的描述使滞后模型值得作为候选进行比较。",
            "translated_to_target": "在目标侧可把需求作为输入、库存作为状态进行候选比较。",
            "concrete_application": "先对齐时间戳，再比较零滞后与多个延迟候选。",
            "source_support": "not_recorded",
            "transfer_status": "untested",
            "prerequisites": ["采样频率一致", "库存序列无缺口"],
            "failure_signal": "延迟候选没有改善留出期预测时停止迁移。",
        }],
        "how_to_combine": {
            "steps": ["对齐需求、订单和库存时间戳。", "在同一留出期比较零滞后与延迟候选。"],
            "assumptions_to_verify": ["需求变化发生在补货变化之前。"],
            "boundary_conditions": ["促销和缺货期间需要单独分层。"],
            "discriminating_experiment": {
                "question": "过冲主要来自反馈延迟还是共同季节趋势？",
                "candidate_hypothesis": "加入补货延迟后可改善留出期解释。",
                "competitor_hypotheses": ["只用季节项即可得到同等解释。"],
                "intervention_or_measurement": "固定数据窗口，比较预注册的零滞后、延迟和季节模型。",
                "primary_outcome": "同一留出期的预测误差",
                "expected_outcomes": [
                    {"hypothesis_id": "delay", "role": "candidate", "expected_observation": "延迟模型误差更低且方向稳定。"},
                    {"hypothesis_id": "season", "role": "competitor", "expected_observation": "季节模型与延迟模型表现相当。"},
                ],
                "confounds": ["促销", "缺货"],
                "minimum_data": "至少覆盖多个补货周期，并预留独立留出期。",
                "procedure": ["冻结模型与指标。", "在同一留出期计算误差并检查残差。"],
                "decision_rule": "仅当候选假设在预注册主指标上优于竞争假设时继续；否则拒绝候选。",
                "falsification_rule": "若候选假设未优于竞争假设，或结果方向与预注册预期相反，则证伪并拒绝候选。",
                "stop_rule": "若最低数据要求、数据质量或安全边界不满足，则停止实验且不作机制结论。",
                "threshold_basis": "proposal",
                "calibration_required": True,
            },
        },
        "research_directions": {
            "literature_status": "not_checked",
            "status_explanation": "未执行外部文献检索；先例与新颖性仍未知。",
            "search_questions": ["哪些研究比较过延迟与季节解释？", "哪些数据能识别反馈方向？"],
            "source_types_to_check": ["同行评审论文", "可复现实证数据"],
            "suggested_references": [],
        },
        "risks_and_limits": [{
            "risk_name": "季节性混杂",
            "severity": "high",
            "explanation": "共同趋势可能同时推动需求和库存。",
            "condition": "促销与节假日集中出现时风险上升。",
            "observable_signal": "加入季节项后延迟效应消失。",
            "stop_rule": "无法分离季节因素时不进入干预。",
        }],
        "action_plan": {
            "intro": "先完成测量与区分，不把候选类比直接当作行动处方。",
            "if_time_short": {"title": "冻结比较方案", "rationale": "没有统一方案就无法解释模型差异。"},
            "this_week": [
                {
                    "rank": 1, "title": "冻结比较方案", "how": "记录数据窗口、模型和留出期。",
                    "hypothesis_id": "delay", "primary_metric": "留出期预测误差",
                    "decision_rule": "仅当预注册主指标提供可区分信息时继续；否则停止并复核候选。",
                    "stop_condition": "若最低数据要求、数据质量或安全边界不满足，则停止该行动。", "expected_information": "知道是否值得继续核查延迟机制。",
                    "estimated_time": "半天", "category": "diagnostic", "threshold_basis": "proposal",
                    "calibration_required": True,
                },
                {
                    "rank": 2, "title": "整理时间序列", "how": "对齐需求、订单和库存的采样时间。",
                    "hypothesis_id": "data", "primary_metric": "连续且同频的观测期数",
                    "decision_rule": "仅当预注册主指标提供可区分信息时继续；否则停止并复核候选。",
                    "stop_condition": "若最低数据要求、数据质量或安全边界不满足，则停止该行动。", "expected_information": "确认数据是否支持区分实验。",
                    "estimated_time": "一天", "category": "measurement", "threshold_basis": "proposal",
                    "calibration_required": True,
                },
            ],
            "review_trigger": "完成留出期比较后再决定是否设计小范围干预。",
        },
    }
