"""W13-E (session #10) Cmd+K palette e2e — site-wide search.

These tests cannot easily boot a real Next.js server in CI, so we mirror
the W12-E PWA test pattern: stand up a tiny `http.server` that serves a
self-contained HTML shell which embeds a minimal-but-faithful JS
implementation of the palette behavior, plus the real `search-index.json`
generated by `scripts/build_search_index.py`.

That lets us assert:
  • Cmd+K opens the palette
  • Ctrl+K opens the palette (cross-platform)
  • Typing "appl" surfaces AAPL as the top result
  • Arrow-Down + Enter navigates to /company/AAPL
  • Esc closes the palette
  • Keyboard shortcut does NOT trigger inside an <input> for bare `/`
  • Cmd+K still works inside an <input> (modifier disambiguates)
  • Mobile viewport renders full-screen
  • Recent searches persist across opens (localStorage)
"""
from __future__ import annotations

import http.server
import json
import socketserver
import subprocess
import sys
import threading
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parents[3]
_PUBLIC = _REPO / "web" / "phase-detector" / "public"
_INDEX_FILE = _PUBLIC / "search-index.json"
_BUILD_SCRIPT = _REPO / "scripts" / "build_search_index.py"


# A self-contained HTML shell that mimics CommandPaletteProvider + CommandPalette.
# Keep this in sync with the React component's testable surface:
#   - data-testid="cmdk-dialog" appears when open
#   - data-testid="cmdk-input"  is the search input
#   - data-testid="cmdk-result-<type>" is each result row
#   - Cmd+K / Ctrl+K toggle
#   - `/` opens IFF not focused inside <input>
#   - Esc closes
#   - Arrow keys navigate, Enter activates
#   - Recent searches via localStorage key "phase:cmdk:recent"
_INDEX_HTML = r"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>CmdK harness</title>
  <style>
    body { font: 14px system-ui; margin: 0; padding: 24px; }
    .cmdk-dialog { position: fixed; inset: 0; background: rgba(0,0,0,.4); display:flex; justify-content:center; align-items:flex-start; }
    .cmdk-panel { background: white; width: 600px; max-width: 100vw; margin-top: 10vh; border-radius: 8px; overflow: hidden; }
    .cmdk-panel input { width: 100%; padding: 12px 16px; border: 0; outline: none; font-size: 16px; }
    .cmdk-list { max-height: 60vh; overflow-y: auto; }
    .cmdk-row { padding: 10px 16px; cursor: pointer; }
    .cmdk-row[aria-selected="true"] { background: #f3f4f6; }
    .cmdk-row .title { font-weight: 500; }
    .cmdk-row .sub { color: #6b7280; font-size: 12px; }
    .cmdk-group { padding: 4px 16px; text-transform: uppercase; color: #9ca3af; font-size: 11px; }
    @media (max-width: 640px) {
      .cmdk-panel { width: 100vw; max-width: none; height: 100dvh; margin-top: 0; border-radius: 0; }
    }
  </style>
</head>
<body>
  <h1 data-testid="home-heading">Harness page</h1>
  <input type="text" data-testid="other-input" placeholder="something else">
  <textarea data-testid="other-textarea"></textarea>

  <div id="cmdk-root"></div>

  <script>
  (function() {
    let isOpen = false;
    let query = "";
    let hits = [];
    let activeIdx = 0;
    let index = null;
    let lastSource = "shortcut";

    const RECENT_KEY = "phase:cmdk:recent";

    function norm(s) { return s.toLowerCase().trim().replace(/\s+/g, " "); }

    function isSubsequence(needle, haystack) {
      if (!needle.length) return true;
      let i = 0;
      for (let j = 0; j < haystack.length && i < needle.length; j++) {
        if (haystack[j] === needle[i]) i++;
      }
      return i === needle.length;
    }

    function daysSince(iso) {
      if (!iso) return Infinity;
      const t = Date.parse(iso);
      if (Number.isNaN(t)) return Infinity;
      return (Date.now() - t) / 86400000;
    }

    function scoreEntry(entry, q) {
      if (!q) return 0;
      const title = norm(entry.title);
      let best = 0;
      if (title === q) best = Math.max(best, 1000);
      else if (title.startsWith(q)) best = Math.max(best, 700);
      else if (title.includes(q)) best = Math.max(best, 300);
      for (const kw of entry.keywords || []) {
        if (kw === q) { best = Math.max(best, 1000); break; }
        else if (kw.startsWith(q)) best = Math.max(best, 500);
        else if (kw.includes(q)) best = Math.max(best, 200);
      }
      if (best === 0 && q.length >= 2 && isSubsequence(q, title)) best = 100;
      if (best === 0) return 0;
      const w = (entry.weight || 0) * 50;
      let rec = 0;
      if ((entry.type === "paper" || entry.type === "newsletter")) {
        const d = daysSince(entry.date);
        if (Number.isFinite(d)) rec = Math.max(0, 20 - d / 18);
      }
      return best + w + rec;
    }

    function searchIndex(idx, q, lim) {
      lim = lim || 8;
      const nq = norm(q);
      if (!nq) return [];
      const out = [];
      for (const e of idx) {
        const s = scoreEntry(e, nq);
        if (s > 0) out.push(Object.assign({}, e, { score: s }));
      }
      out.sort((a, b) => b.score - a.score);
      return out.slice(0, lim);
    }

    async function ensureIndex() {
      if (index) return index;
      const r = await fetch("/search-index.json");
      index = await r.json();
      return index;
    }

    function loadRecent() {
      try { return JSON.parse(localStorage.getItem(RECENT_KEY) || "[]"); } catch { return []; }
    }
    function pushRecent(q) {
      const t = (q || "").trim();
      if (!t) return;
      const prev = loadRecent();
      const next = [t].concat(prev.filter(p => p !== t)).slice(0, 5);
      localStorage.setItem(RECENT_KEY, JSON.stringify(next));
    }

    function open_(source) {
      isOpen = true;
      lastSource = source || "shortcut";
      ensureIndex().then(render).catch(render);
      // emit a tracked event marker for tests
      window.__cmdk_events = window.__cmdk_events || [];
      window.__cmdk_events.push({ event: "search_opened", source: lastSource });
      render();
    }
    function close_() {
      isOpen = false;
      query = "";
      activeIdx = 0;
      hits = [];
      render();
    }

    function go(hit, pos) {
      window.__cmdk_events = window.__cmdk_events || [];
      window.__cmdk_events.push({
        event: "search_result_click",
        result_type: hit.type,
        result_position: pos,
      });
      pushRecent(query || hit.title);
      // simulate router.push by replacing URL hash for testability.
      window.location.hash = "go=" + encodeURIComponent(hit.url);
      close_();
    }

    function render() {
      const root = document.getElementById("cmdk-root");
      if (!isOpen) { root.innerHTML = ""; return; }
      hits = searchIndex(index || [], query, 8);
      if (activeIdx >= hits.length) activeIdx = Math.max(0, hits.length - 1);

      // group order
      const groupOrder = ["company", "universality_class", "paper", "newsletter", "docs"];
      const groupLabels = {
        company: "公司", universality_class: "普适类",
        paper: "论文", newsletter: "周刊", docs: "文档",
      };
      const grouped = {};
      for (const t of groupOrder) grouped[t] = [];
      hits.forEach(h => { (grouped[h.type] = grouped[h.type] || []).push(h); });

      let pos = -1;
      let html = '';
      for (const t of groupOrder) {
        if (!grouped[t] || !grouped[t].length) continue;
        html += '<div class="cmdk-group">' + groupLabels[t] + '</div>';
        for (const h of grouped[t]) {
          pos += 1;
          const sel = (pos === activeIdx);
          html += '<div class="cmdk-row" role="option" '
               + 'aria-selected="' + sel + '" '
               + 'data-cmdk-pos="' + pos + '" '
               + 'data-cmdk-url="' + h.url + '" '
               + 'data-testid="cmdk-result-' + h.type + '">'
               + '<div class="title">' + h.title + '</div>'
               + '<div class="sub">' + h.subtitle + '</div>'
               + '</div>';
        }
      }
      if (!hits.length && query.trim()) html = '<div style="padding:24px;color:#6b7280">没有匹配 “' + query + '” 的结果</div>';
      if (!query.trim()) {
        const recent = loadRecent();
        html = '';
        if (recent.length) {
          html += '<div class="cmdk-group">最近搜索</div>';
          recent.forEach(r => {
            html += '<div class="cmdk-row" data-cmdk-recent="' + r + '">' + r + '</div>';
          });
        }
        html += '<div class="cmdk-group">热门</div>'
              + '<div class="cmdk-row" data-cmdk-trending="AAPL">AAPL</div>'
              + '<div class="cmdk-row" data-cmdk-trending="scheffer">Scheffer fold</div>';
      }

      root.innerHTML =
        '<div class="cmdk-dialog" role="dialog" aria-modal="true" data-testid="cmdk-dialog">'
        + '<div class="cmdk-panel">'
        + '<input type="text" data-testid="cmdk-input" role="combobox" '
        + ' aria-controls="cmdk-listbox" placeholder="搜公司、普适类…" autofocus>'
        + '<div class="cmdk-list" role="listbox" id="cmdk-listbox" data-testid="cmdk-list">' + html + '</div>'
        + '</div></div>';

      const input = root.querySelector('[data-testid="cmdk-input"]');
      input.value = query;
      setTimeout(() => input.focus(), 0);

      input.addEventListener("input", e => {
        query = e.target.value;
        window.__cmdk_events = window.__cmdk_events || [];
        window.__cmdk_events.push({
          event: "search_query",
          query_length: query.length,
          result_count: searchIndex(index || [], query, 8).length,
        });
        activeIdx = 0;
        render();
      });

      root.querySelectorAll('[data-cmdk-recent]').forEach(el => {
        el.addEventListener("click", () => { query = el.getAttribute("data-cmdk-recent"); render(); });
      });
      root.querySelectorAll('[data-cmdk-trending]').forEach(el => {
        el.addEventListener("click", () => { query = el.getAttribute("data-cmdk-trending"); render(); });
      });
      root.querySelectorAll('.cmdk-row[role="option"]').forEach(el => {
        el.addEventListener("click", () => {
          const pos = parseInt(el.getAttribute("data-cmdk-pos"), 10);
          go(hits[pos], pos);
        });
      });
    }

    function isEditingTarget(t) {
      if (!t || !t.tagName) return false;
      const tag = t.tagName;
      if (tag === "INPUT" || tag === "TEXTAREA" || tag === "SELECT") return true;
      if (t.isContentEditable) return true;
      return false;
    }

    document.addEventListener("keydown", (e) => {
      // Cmd+K / Ctrl+K — toggle (works even inside other inputs)
      if ((e.metaKey || e.ctrlKey) && (e.key === "k" || e.key === "K")) {
        e.preventDefault();
        isOpen ? close_() : open_("shortcut");
        return;
      }
      // Bare `/` — only when not inside a text field
      if (e.key === "/" && !isEditingTarget(e.target) && !e.metaKey && !e.ctrlKey && !e.altKey) {
        e.preventDefault();
        isOpen ? close_() : open_("shortcut");
        return;
      }
      if (!isOpen) return;
      if (e.key === "Escape") { e.preventDefault(); close_(); return; }
      if (e.key === "ArrowDown") {
        e.preventDefault();
        activeIdx = Math.min(activeIdx + 1, Math.max(0, hits.length - 1));
        render();
        return;
      }
      if (e.key === "ArrowUp") {
        e.preventDefault();
        activeIdx = Math.max(0, activeIdx - 1);
        render();
        return;
      }
      if (e.key === "Enter") {
        e.preventDefault();
        const t = hits[activeIdx];
        if (t) go(t, activeIdx);
      }
    });

    // Expose API for /search-style deep-link test:
    window.__cmdk_open = open_;
    window.__cmdk_close = close_;
  })();
  </script>
</body>
</html>
"""


class _SilentHandler(http.server.SimpleHTTPRequestHandler):
    def log_message(self, *_a, **_kw):
        return

    def do_GET(self):  # noqa: N802
        path = self.path.split("?", 1)[0]
        if path in ("/", "/index.html", "/search"):
            self._send(200, "text/html; charset=utf-8", _INDEX_HTML.encode("utf-8"))
            return
        if path == "/search-index.json" and _INDEX_FILE.is_file():
            self._send(200, "application/json", _INDEX_FILE.read_bytes())
            return
        self._send(404, "text/plain", b"not found")

    def _send(self, status, ctype, body):
        self.send_response(status)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


@pytest.fixture(scope="module")
def index_built():
    """Ensure search-index.json exists for the harness fetch()."""
    if not _INDEX_FILE.is_file():
        subprocess.run(
            [sys.executable, str(_BUILD_SCRIPT)],
            cwd=_REPO,
            check=True,
            capture_output=True,
        )
    assert _INDEX_FILE.is_file(), "search-index.json should exist after build"
    return _INDEX_FILE


@pytest.fixture(scope="module")
def server(index_built):
    """Boot tiny HTTP server on an ephemeral port for the module."""
    httpd = socketserver.TCPServer(("127.0.0.1", 0), _SilentHandler)
    port = httpd.server_address[1]
    th = threading.Thread(target=httpd.serve_forever, daemon=True)
    th.start()
    yield f"http://127.0.0.1:{port}"
    httpd.shutdown()
    httpd.server_close()


# ----------------------------------------------------------------------
# Sanity: index built & reachable
# ----------------------------------------------------------------------

@pytest.mark.sanity
def test_index_has_minimum_entries(index_built):
    data = json.loads(index_built.read_text())
    assert isinstance(data, list)
    assert len(data) >= 130, f"index too small: {len(data)} < 130"
    types = {e["type"] for e in data}
    assert {"company", "universality_class", "paper", "docs"}.issubset(types)


@pytest.mark.sanity
def test_aapl_entry_present(index_built):
    data = json.loads(index_built.read_text())
    aapl = next((e for e in data if e["id"] == "company-AAPL"), None)
    assert aapl is not None, "AAPL company entry missing"
    assert aapl["url"] == "/company/AAPL"
    assert "apple" in aapl["keywords"]


# ----------------------------------------------------------------------
# Playwright e2e
# ----------------------------------------------------------------------

@pytest.mark.e2e
def test_cmdk_opens_palette(page, server):
    page.goto(server)
    # No dialog visible initially.
    assert page.locator('[data-testid="cmdk-dialog"]').count() == 0
    # Cmd+K opens it (Playwright maps Meta to Cmd on Mac, Ctrl on Linux).
    page.keyboard.press("Meta+k")
    page.locator('[data-testid="cmdk-dialog"]').wait_for(state="visible", timeout=2000)
    assert page.locator('[data-testid="cmdk-input"]').is_visible()


@pytest.mark.e2e
def test_ctrl_k_also_opens_palette(page, server):
    page.goto(server)
    page.keyboard.press("Control+k")
    page.locator('[data-testid="cmdk-dialog"]').wait_for(state="visible", timeout=2000)


@pytest.mark.e2e
def test_typing_appl_surfaces_aapl(page, server):
    page.goto(server)
    page.keyboard.press("Meta+k")
    page.locator('[data-testid="cmdk-input"]').wait_for(state="visible")
    page.locator('[data-testid="cmdk-input"]').fill("appl")
    # Wait a tick for the search to render.
    page.wait_for_timeout(100)
    first = page.locator('[data-testid="cmdk-result-company"]').first
    first.wait_for(state="visible", timeout=2000)
    # Top company result should be Apple.
    title = first.locator(".title").inner_text()
    assert "AAPL" in title or "Apple" in title, f"expected AAPL top, got {title!r}"


@pytest.mark.e2e
def test_arrow_enter_navigates(page, server):
    page.goto(server)
    page.keyboard.press("Meta+k")
    page.locator('[data-testid="cmdk-input"]').wait_for(state="visible")
    page.locator('[data-testid="cmdk-input"]').fill("appl")
    page.wait_for_timeout(100)
    page.keyboard.press("Enter")
    # Harness simulates router.push by setting window.location.hash.
    page.wait_for_function(
        "() => window.location.hash.startsWith('#go=')", timeout=2000
    )
    h = page.evaluate("() => decodeURIComponent(window.location.hash)")
    assert "/company/AAPL" in h, f"expected /company/AAPL, got {h!r}"


@pytest.mark.e2e
def test_esc_closes(page, server):
    page.goto(server)
    page.keyboard.press("Meta+k")
    page.locator('[data-testid="cmdk-dialog"]').wait_for(state="visible")
    page.keyboard.press("Escape")
    page.locator('[data-testid="cmdk-dialog"]').wait_for(state="hidden", timeout=2000)


@pytest.mark.e2e
def test_slash_does_not_trigger_inside_input(page, server):
    page.goto(server)
    # Focus an existing input.
    page.locator('[data-testid="other-input"]').click()
    page.keyboard.press("/")
    # Palette must NOT have opened.
    assert page.locator('[data-testid="cmdk-dialog"]').count() == 0
    # But the `/` was typed into the input.
    val = page.locator('[data-testid="other-input"]').input_value()
    assert val == "/"


@pytest.mark.e2e
def test_cmd_k_still_works_inside_input(page, server):
    """Cmd+K should override even when an <input> has focus."""
    page.goto(server)
    page.locator('[data-testid="other-input"]').click()
    page.keyboard.press("Meta+k")
    page.locator('[data-testid="cmdk-dialog"]').wait_for(state="visible", timeout=2000)


@pytest.mark.e2e
def test_mobile_viewport_renders_palette(playwright_instance, server):
    browser = playwright_instance.chromium.launch(headless=True)
    try:
        # iPhone 12 dimensions.
        ctx = browser.new_context(viewport={"width": 390, "height": 844})
        pg = ctx.new_page()
        pg.goto(server)
        pg.keyboard.press("Meta+k")
        pg.locator('[data-testid="cmdk-dialog"]').wait_for(state="visible", timeout=2000)
        # Panel should fill the viewport (full-screen mobile).
        bbox = pg.locator(".cmdk-panel").bounding_box()
        assert bbox is not None
        assert bbox["width"] >= 380, f"mobile panel width too narrow: {bbox['width']}"
        ctx.close()
    finally:
        browser.close()


@pytest.mark.e2e
def test_recent_searches_persist(page, server):
    page.goto(server)
    page.keyboard.press("Meta+k")
    page.locator('[data-testid="cmdk-input"]').wait_for(state="visible")
    page.locator('[data-testid="cmdk-input"]').fill("appl")
    page.wait_for_timeout(100)
    page.keyboard.press("Enter")
    page.wait_for_function("() => window.location.hash.startsWith('#go=')", timeout=2000)

    # Reopen — recent list should include "appl".
    page.keyboard.press("Meta+k")
    page.locator('[data-testid="cmdk-dialog"]').wait_for(state="visible")
    recent = page.locator('[data-cmdk-recent="appl"]')
    assert recent.count() == 1, "recent search 'appl' should be in the list"


@pytest.mark.e2e
def test_plausible_events_fired(page, server):
    """Verify the three tracked event types fire."""
    page.goto(server)
    page.keyboard.press("Meta+k")
    page.locator('[data-testid="cmdk-input"]').wait_for(state="visible")
    page.locator('[data-testid="cmdk-input"]').fill("aapl")
    page.wait_for_timeout(200)
    page.keyboard.press("Enter")
    page.wait_for_function("() => window.location.hash.startsWith('#go=')", timeout=2000)

    events = page.evaluate("() => window.__cmdk_events || []")
    names = {e["event"] for e in events}
    assert "search_opened" in names, "missing search_opened event"
    assert "search_query" in names, "missing search_query event"
    assert "search_result_click" in names, "missing search_result_click event"
